language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm install
  - php artisan key:generate
  - gulp
  
deploy:
  provider: heroku
  app: lippep-laravel-5-angular-2
  api-key:
    secure: $HEROKU_API_KEY