language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - npm install
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  
deploy:
  provider: heroku
  app: lippep-laravel-5-angular-2
  api-key:
    secure: $HEROKU_API_KEY